[package]
name = "smali_disassembler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "2.2.0"
dex = "0.5.0"

[dev-dependencies] 
zip = "2.2.0"
dex = "0.5.0"
